dist: trusty
sudo: false

language: go

before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
  - make dependencies
  - make build
  - make coverage
  - $GOPATH/bin/goveralls -coverprofile overalls.coverprofile -service=travis-ci

go:
  - 1.8
