dist: trusty
sudo: false

language: go

before_install:
  - go get github.com/mattn/goveralls

install:
  - ./build-sqlite.sh

script:
  - export CGO_CFLAGS="-I$(pwd)/.sqlite/"
  - export CGO_LDFLAGS="-L$(pwd)/.sqlite/.libs"
  - export TAGS="libsqlite3 linux"
  - export LD_LIBRARY_PATH=$(pwd)/.sqlite/.libs
  - export COV_PREFIX=
  - go get -tags "$TAGS" ./...
  - go build -tags "$TAGS" ./...
  - >-
      echo "mode: count" > out.cov
  - go test -v -tags "$TAGS" ./connection -covermode=count -coverprofile=tmp.cov
  - tail -n +2 tmp.cov >> out.cov
  - go test -v -tags "$TAGS" ./transaction -covermode=count -coverprofile=tmp.cov
  - tail -n +2 tmp.cov >> out.cov
  - go test -v -tags "$TAGS" ./command -covermode=count -coverprofile=tmp.cov
  - tail -n +2 tmp.cov >> out.cov
  - go test -v -tags "$TAGS" ./replication -covermode=count -coverprofile=tmp.cov
  - tail -n +2 tmp.cov >> out.cov
  - go test -v -tags "$TAGS" . -covermode=count -coverprofile=tmp.cov
  - tail -n +2 tmp.cov >> out.cov
  - $HOME/gopath/bin/goveralls -coverprofile out.cov -service=travis-ci

cache:
  directories:
    - .sqlite

go:
  - 1.8
